version: '3.12'


services:
  app:
    build:
      context: .
      dockerfile: "app/Dockerfile"
    container_name: "request_rate_limit"
    env_file:
      - ".env.docker"
    restart: "always"
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    container_name: "redis"
    image: "redis:alpine"
    ports:
      - "6378:6379"